admin_custom/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.contrib.auth import views as auth_views
app_name='admin_custom'
urlpatterns = [
path('admin_product/',views.product_table,name='admin_product'),
path('admin_order/',views.order_table,name='admin_order'),
path('admin_other/',views.admin_other,name='admin_other'),
path('add_product/',views.add_product,name='add_product'),
path('add_size/',views.add_size,name='add_size'),
path('add_category/',views.add_category,name='add_category'),
path('add_banner/',views.add_banner,name='add_banner'),
path('edit_banner/',views.edit_banner,name='edit_banner'),
path('delete_product/',views.delete_product,name='delete_product'),
path('delete_order/',views.delete_order,name='delete_order'),
path('delete_other/',views.delete_other,name='delete_other'),
path('edit_product/<int:product_id>/',views.edit_product,name='edit_product'),
path('edit_order/<int:order_id>/',views.edit_order,name='edit_order'),
path('edit_about',views.edit_about_contact,name='edit_about'),
path('login/',views.sign_in,name='login'),
path('logout/',views.sign_out,name='logout'),
path('signup/', views.sign_up,name="sign_up"),
]

shoe_store/shoe_store/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

shoe_store/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("store.urls")),
    path("admin_custom/",include("admin_custom.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views
app_name='shoe_store'
urlpatterns = [
    path('',views.main_shop,name='index'),
    path('trang-chu/',views.main_shop,name='index'),
    path('cua-hang/<slug:category>/', views.shop,name ="shop"),
    path('san-pham/<int:product_id>/', views.product_detail,name= "product_detail"),
     path('tim-kiem/', views.search,name= "search"),
    path('gio-hang/', views.cart,name= "cart"),
    path('thanh-toan/',views.checkout,name="checkout"),
    path('add_cart/',views.add_cart,name="add_cart"),
    path('remove_cart/',views.remove_cart,name="remove_cart"),
]

admin_custom/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils.html import escape
from django.utils.html import mark_safe


TEL_BANNER = '1'
FORM_BANNER = '2'
IMAGE_BANNER = '3'
WEB_BANNER_TYPE = (
    (TEL_BANNER, "Phone-Input Banner"),
    (FORM_BANNER, "Form Banner"),
    (IMAGE_BANNER, "Image-Only Banner"),
)
SALE_PERCENT = (
    ('0',"Không"),
    ('10',"10%"),
    ('20',"20%"),
    ('30',"30%"),
    ('40',"40%"),
    ('50',"50%"),
    ('60',"60%"),
    ('70',"70%"),
    ('80',"80%"),
    ('90',"90%"),
)
STATUS = (
    ('normal',"NORMAL"),
    ('sale',"SALE"),
    ("new",'NEW')
)
STATUS_ORDER =(
    ('new',"Đơn chưa xử lý"),
    ('accepted','Đã nhận đơn'),
    ('ship',"Đang trên đường vận chuyển"),
    ("complated",'Đã hoàn thành')
)

# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=255,default='')
    slug = models.CharField(max_length=255,default='')
    activate = models.BooleanField(default=True)
    def __str__(self):
        return self.title

class Product(models.Model):
    name = models.CharField(max_length=255,default='')
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    price = models.IntegerField(default=0)
    sale_percent =models.CharField(choices=SALE_PERCENT,max_length=10,default=1)
    accurate_price = models.IntegerField(default=0)
    fabric = models.CharField(max_length=50,default='')
    describe = models.CharField(max_length=255,default='Miêu tả',null=True)
    status = models.CharField(choices=STATUS,max_length=50,default='normal')
    activate = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now=True)
   
    def __str__(self):
        if self.name:
            return self.name
class size_product(models.Model):
    size = models.CharField(max_length=10,default='')
    def __str__(self):
        return self.size   
    
class product_variants(models.Model):
    product_id = models.ForeignKey(Product,on_delete=models.CASCADE)
    size = models.ForeignKey(size_product,on_delete=models.CASCADE)
    quantity  = models.IntegerField(null=False, blank=False)
    sku = models.CharField(max_length=10,default='')
    
  
class Img_product(models.Model):
    id_product = models.ForeignKey(Product,on_delete=models.CASCADE)
    img = models.ImageField( upload_to="products/%Y/%m%d",null=True, blank=True)
    def __str__(self):
        return self.id_product.name
    

    
class Order(models.Model):
    customer_name = models.CharField(max_length=255,default='',null=True,blank=True)
    shipping_address = models.CharField(max_length=255,default='',null=True,blank=True)
    phone_number = models.CharField(max_length=11,default='',null=True,blank=True)
    email = models.EmailField(max_length=254,null=True,blank=True)
    order_description = models.TextField(max_length=255,default='')
    total_price = models.CharField(max_length=255,default='',null=True,blank=True)
    status = models.CharField(choices=STATUS_ORDER ,max_length=10,default='new')
    order_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return str(self.id)
    
class Order_detail(models.Model):
    order = models.ForeignKey(Order,on_delete=models.CASCADE)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    size = models.CharField(max_length=10,null=False, blank=True)
    quantity  = models.IntegerField(null=False, blank=True,default=1)
    def image_tag(self):
            img = Img_product.objects.filter(id_product = self.product).first()
            return mark_safe('<img src="%s" width="125" height="150" />' % (img.img.url))
    image_tag.short_description = 'Image'
    
    
class Banner(models.Model):
    title = models.CharField(
        max_length=255, null=True, blank=True)
    order = models.IntegerField(null=True)
    image = models.ImageField(
        upload_to="banners/%Y/%m%d",
        null=True, blank=True,
        verbose_name=_("Ảnh")
    )
    is_activate  = models.BooleanField(
        default=True, verbose_name="Active", help_text="Active banner", null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    def __str__(self):
        if self.title:
            return self.title
        else:
            return "Banner "+str(self.id)
        
class About_contact(models.Model):
    title = models.CharField(max_length=255,default='',null=True,blank=True)
    about_describe = models.CharField(max_length=255,default='',null=True,blank=True)
    last_mes = models.CharField(max_length=255,default='',null=True,blank=True)
    facebook =  models.CharField(max_length=255,default='',null=True,blank=True)
    instagram = models.CharField(max_length=255,default='',null=True,blank=True)
    

admin_custom/views.py
from django.shortcuts import render,redirect
from django.urls import reverse
from django.contrib.auth.models import User
from .models import *
from django.contrib.auth import authenticate, login,logout
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from .forms import *
from django.forms import inlineformset_factory
from django.contrib import messages
from django.conf import settings
from django.contrib.auth.models import User
from django.core.paginator import Paginator
# Create your views here.
nav_activate  = 'bg-gradient-primary'
@login_required(login_url=settings.LOGIN_ULR, redirect_field_name=settings.REDIRECT_FIELD_NAME)
def product_table(request):
    sort_type = request.GET.get('sort_type', 'all')
    print(sort_type)
    if sort_type == "all":
        list_product = Product.objects.filter(activate = True).order_by('created_at')
    elif sort_type == "sale":
        list_product = Product.objects.filter(activate = True, status ='sale').order_by('created_at')
    else:
        list_product = Product.objects.filter(activate = True, category__id = sort_type).order_by('created_at')
        sort_type = int(sort_type) 
    category = Category.objects.filter(activate = True)
    context = {
        'list_product' : list_product,
        'category' : category,
        'sort_type' : sort_type,
        'product_activate' :  nav_activate
    }
    return render(request,'admin_custom/admin_product.html',context)

@login_required(login_url=settings.LOGIN_ULR, redirect_field_name=settings.REDIRECT_FIELD_NAME)
def add_product(request):
    size = size_product.objects.all()
    if request.method == "POST":
        form = FormProduct(request.POST)
        form_set = ProductFormsetVariant(request.POST or None)
        form_set_img = ProductFormsetImg(request.POST,request.FILES)
      
        if form.is_valid() and form_set.is_valid() and form_set_img.is_valid():
            new_product_id = form.save()
            form_set.save(commit=False)
            form_set_img.save(commit=False)
            form_set_img.instance = new_product_id
            form_set_img.save()
            form_set.instance = new_product_id
            form_set.save()
            messages.success(request, ('Thêm mới thành công!'))
            return redirect(reverse('admin_custom:admin_product'))
        else:
            messages.error(request, ('Đã xảy ra lỗi!'))
            context = {
            'form' : form,
            'size' : size,
            'form_set' : form_set,
            'form_set_img' : form_set_img,
            'product_activate' :  nav_activate
                } 
            return render(request,'admin_custom/add_product.html',context)
    form = FormProduct()
    form_set = ProductFormsetVariant
    form_set_img = ProductFormsetImg
    context = {
        'form' : form,
        'size' : size,
        'form_set' : form_set,
        'form_set_img' : form_set_img
    }   
    return render(request,'admin_custom/add_product.html',context)

@login_required(login_url=settings.LOGIN_ULR, redirect_field_name=settings.REDIRECT_FIELD_NAME)
def edit_product(request,product_id):
    product = Product.objects.get(id = product_id)
    size = size_product.objects.all().order_by('size')
    if request.method == "POST":
        form = FormProduct(request.POST,instance=product)
        form_set = ProductFormsetVariant(request.POST or None,instance=product)
        form_set_img = ProductFormsetImg(request.POST,request.FILES,instance=product)
        if form.is_valid() and form_set.is_valid() and form_set_img.is_valid():
            form.save()
            form_set_img.save()
            form_set.save()
            messages.success(request, ('Chỉnh sửa thành công!'))
            return redirect(reverse('admin_custom:admin_product'))
        else:
            context = {
            'product_id' : product_id,
            'form' : form,
            'size' : size,
            'form_set' : form_set,
            'form_set_img' : form_set_img
                } 
            return render(request,'admin_custom/add_product.html',context)

    form = FormProduct(instance=product)
    form_set = ProductFormsetVariant(instance=product)
    form_set_img = ProductFormsetImg( instance=product)
    context = {
        'product_id' : product_id,
        'form' : form,
        'size' : size,
        'form_set' : form_set,
        'form_set_img' : form_set_img,
    } 
    return render(request,'admin_custom/edit_product.html',context)
@login_required(login_url=settings.LOGIN_ULR, redirect_field_name=settings.REDIRECT_FIELD_NAME)
def delete_product(request):
    if request.method == "POST":
        product_id= request.POST.get('product_id_delete')
        print(product_id)
        if product_id is not None:
            try:
                Product.objects.get(id=product_id).delete()
            except Exception as e:
                print(e)
            messages.success(request, ('Xóa sản phẩm thành công!'))
        else:
            messages.error(request, ('Sản phẩm chưa thể xóa!'))
        return redirect(reverse('admin_custom:admin_product'))
    else:
        return redirect(reverse('admin_custom:admin_product')) 
    
    
@login_required(login_url=settings.LOGIN_ULR, redirect_field_name=settings.REDIRECT_FIELD_NAME)
def order_table(request):
    status = STATUS_ORDER
    sort_type = request.GET.get('sort_type', 'all')
    if sort_type == "all":
        order = Order.objects.all().order_by('-order_at')
    else:
        order = Order.objects.filter(status  = sort_type).order_by('-order_at')
    context ={
        'order' : order,
        'sort_type' : sort_type,
        'status' : status,
        'order_activate' :  nav_activate
    }
    return render(request,'admin_custom/admin_order.html',context)

@login_required(login_url=settings.LOGIN_ULR, redirect_field_name=settings.REDIRECT_FIELD_NAME)
def edit_order(request,order_id):
    size = size_product.objects.all()
    order = Order.objects.get(id= order_id)
    form = FormOrder(request.POST or None,instance = order)
    order_detail  =Order_detail.objects.filter(order = order_id)
    form_set = OrderFormset(request.POST or None,instance = order)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            messages.success(request, ('Chỉnh sửa thành công!'))
            return redirect(reverse('admin_custom:admin_order'))
        else:
            context = {
            'form' : form,
            'size' : size,
            'order_id' : order_id,
            'order_detail' : order_detail 
            }
            return render(request,'admin_custom/edit_order.html',context)
    context = {
        'form' : form,
        'form_set' : form_set,
        'size' : size,
        'order_id' : order_id,
        'order_detail' : order_detail 
     }
    return render(request,'admin_custom/edit_order.html',context)
    
@login_required(login_url=settings.LOGIN_ULR, redirect_field_name=settings.REDIRECT_FIELD_NAME)
def delete_order(request):
    if request.method == "POST":
        order_id =  request.POST.get('order_id_delete')
        if order_id is not None:
            try:
                Order.objects.get(id=order_id).delete()
            except Exception as e:
                print(e)
            messages.success(request, ('Xóa đơn hàng thành công!'))
        else:
            messages.error(request, ('Đơn hàng chưa thể xóa!'))
        return redirect(reverse('admin_custom:admin_order'))
    else:
        return redirect(reverse('admin_custom:admin_order')) 
    
@login_required(login_url=settings.LOGIN_ULR, redirect_field_name=settings.REDIRECT_FIELD_NAME)
def admin_other(request):
    about = About_contact.objects.all()
    about_instance =  About_contact.objects.all().first()
    size = size_product.objects.all().order_by('size')
    category = Category.objects.all().order_by('id')
    banner =  Banner.objects.all().order_by('order')
    form_about = FormAboutContact(instance=about_instance)
    form_size = FormSize()
    form_category = FormCategory()
    form_banner = FormBanner()
    context = {
    'about' : about,
    'size' :size,
    'banner' : banner,
    'other_activate' :  'other_activate',
    'form_about' :  form_about,
    'form_size'  : form_size,
    'form_banner' : form_banner,
    'category' : category,
    'form_category' : form_category 
    }
    return render(request,'admin_custom/other_table.html',context)

@login_required(login_url=settings.LOGIN_ULR, redirect_field_name=settings.REDIRECT_FIELD_NAME)
def delete_other(request):
    if request.method == "POST":
        other_id =  request.POST.get('other_id_delete')
        check_delete = request.POST.get('check_delete', None)
        if other_id is not None and check_delete is not None:
            if check_delete == 'about':
                try:
                    About_contact.objects.get(id=other_id).delete()
                except Exception as e:
                    print(e)
                messages.success(request, ('Xóa thành công!'))
            elif check_delete == 'size':
                try:
                    size_product.objects.get(id=other_id).delete()
                except Exception as e:
                    print(e)
                messages.success(request, ('Xóa thành công!'))       
            elif check_delete == 'banner':
                try:
                    Banner.objects.get(id=other_id).delete()
                except Exception as e:
                    print(e)
                messages.success(request, ('Xóa thành công!'))
            else:
                try:
                    Category.objects.get(id=other_id).delete()
                except Exception as e:
                    print(e)
                messages.success(request, ('Xóa thành công!'))
        else:
            messages.error(request, ('Chưa thể xóa!'))

templates/admin_custom/admin_product.html
{% extends 'admin_custom/base.html' %}
{% load static %}
{% load admin_tags %}
{% block body_content %}
  <div class="row">
    <div class=" position-relative max-height-vh-100 h-100 border-radius-lg offset-3 col-3 offset-md-3 col-md-9 offset-xl-2 col-xl-10 min-vh-100 px-5 offset-lg-2 col-lg-10">
      {% if messages %}
      {% for message in messages %}
      <div class="row">
        <div class="align-middle text-center alert alert-{{ message.tags}} fade show  mt-2 mb-2  offset-md-4 col-md-4" role="alert" style="max-width:290px;">
          <strong style="color:white;">{{message}}</strong> 
          <button type="button" class="close" data-dismiss="alert" aria-label="Close" style="">
            <span aria-hidden="true">X</span>
          </button>
      </div>
   
      {% endfor %}
      {% endif %}    
      <div class="container-fluid py-4">
        <div class="row">
          <div class="col-12">
            <div class="card my-4">
              <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                  <h6 class="text-white text-capitalize ps-3">Tất cả giày</h6>
                </div>
              </div>
              <div class="row">
                <div class="offset-lg-8 col-lg-2 offset-2 col-4 mt-4">
                  <div class="d-flex  align-items-center justify-content-lg-end">
                    <strong class="mr-3">Sắp xếp:</strong>
                    <form method="GET" action="{% url 'admin_custom:admin_product' %}" id="admin_product_filter">
                      <select class="" required name="sort_type">
                        <option value="all" {% if sort_type == 'all' %} selected{% endif %}>Tất cả</option>
                        <option value="sale" {% if sort_type == 'sale' %} selected{% endif %}>Sale</option>

                        {% for item in  category %}
                        <option value="{{item.id}}" {% if item.id == sort_type %} selected{% endif %}>{{item.title}}</option>
                        {% endfor %}
                      </select>
                    </form>
                  </div>
              </div>
                <a type="button" class="btn btn-success mt-3 col-4  col-lg-2" href="{% url 'admin_custom:add_product' %}" style="max-width: 200px;">+Thêm sản phẩm </a>
               <div class="card-body px-0 pb-2">
                <div class="table-responsive p-0">
                  <table class="table align-items-center mb-0">
                    <thead>
                      <tr>
                        <th class="text-uppercase text-secondary text-xs font-weight-bolder opacity-7">TÊN</th>
                        <th class="text-uppercase text-secondary text-xs font-weight-bolder opacity-7 ps-1">Giá gốc(VNĐ)</th>
                        <th class="text-uppercase text-secondary text-xs font-weight-bolder opacity-7 ps-0">Giá hiện tại(VNĐ)</th>
                        <th class="text-center text-uppercase text-secondary text-xs font-weight-bolder opacity-7">Trạng thái</th>
                        <th class="text-center text-uppercase text-secondary text-xs font-weight-bolder opacity-7"></th>
                        <th class="text-secondary opacity-7 "></th>
        
                      </tr>
                    </thead>
                    <tbody>
                      {% for  item in list_product  %}
                      <tr>
                        <td>
                          <div class="d-flex px-2 py-1">
                            <div>
                              <img src="{% get_img_product item.id %}" class="avatar avatar-xl me-3 border-radius-lg" alt="user1">
                            </div>
                            <div class="d-flex flex-column justify-content-center">
                              <h6 class="mb-0 text-sm">{{item.name}}</h6>
                      
                            </div>
                          </div>
                        </td>
                        <td>
                          <p class="text-xs font-weight-bold mb-0">{{item.price}}</p>
                          <p class="text-xs text-secondary mb-0"></p>
                        </td>
                        <td>
                          <p class="text-xs font-weight-bold mb-0">{{item.accurate_price}}</p>
                          <p class="text-xs text-secondary mb-0"></p>
                        </td>
                        <td class="align-middle text-center text-sm">
                          {% if item.status == 'sale' %}
                          <span class="badge badge-sm bg-gradient-danger">{{item.status}}</span>
                          {% else %}
                          <span class="badge badge-sm bg-gradient-success">{{item.status}}</span>
                          {% endif %}
                        </td>
                        <td class="align-middle text-center">
                          <a href="{% url 'admin_custom:edit_product' item.id %}" class="text-info  font-weight-bold text-xs" data-toggle="tooltip" data-original-title="Edit user">
                            Edit
                          </a>
                          
                        </td>
                        <td class="align-middle">
                          <a href="" class="text-primary font-weight-bold text-xs btn-delete-product" data-id="{{item.id}}" data-toggle="modal" data-target="#exampleModal">
                            Delete
                          </a>
                        </td>
                      
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
        
       
    </div>
 
      
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Tiệm giày chất</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="border:none;">
            <span aria-hidden="true">X</span>
          </button>
        </div>
        <form action="{% url 'admin_custom:delete_product' %}" method="POST">
          {% csrf_token %}
          <div class="modal-body">
            <input type="text" value="" name="product_id_delete" id="product_id_delete" hidden>
            <p>Bạn chắn chắn xóa sản phẩm này?</p>
          </div>
          <div class="modal-footer">
            <button type="submit" class="btn btn-danger">Chắc chắn</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
            
          </div>
        </form>
      </div>
    </div>
  </div>

   </div>   
{% endblock body_content %}

{% block extra-js %}
<script>

  $('#admin_product_filter').find('select').change(function() {
    $('#admin_product_filter').submit()
  });
  $(".btn-delete-product").click(function(){
    let product_id = $(this).data('id');
    $('#product_id_delete').val(product_id)
  });
</script>
{% endblock %}

templates/admin_custom/navbar.html
{% load static %}

<div class="row">
  <div class="col-3  col-md-3 col-lg-3 col-xl-2">
    <div class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3  bg-gradient-dark" id="sidenav-main">
      <div class="sidenav-header">
        <i class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none" aria-hidden="true" id="iconSidenav"></i>
        <a class="navbar-brand m-0" href=" https://demos.creative-tim.com/material-dashboard/pages/dashboard " target="_blank">
          <img src="{% static 'admin_custom/img/logos/logo1.jpg' %}" class="navbar-brand-img h-100" alt="main_logo">
          <span class="ms-1 font-weight-bold text-white">Tiệm giày chất</span>
        </a>
      </div>
      <hr class="horizontal light mt-0 mb-2">
      <div class="collapse navbar-collapse  w-auto " id="sidenav-collapse-main">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link text-white {% if product_activate %} bg-gradient-primary{% endif %}" href="{% url 'admin_custom:admin_product' %}">
              <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                <i class="material-icons opacity-10">table_view</i>
              </div>
              <span class="nav-link-text ms-1">Sản phẩm </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white{% if order_activate %} bg-gradient-primary {% endif %} " href="{% url 'admin_custom:admin_order' %}">
              <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                <i class="material-icons opacity-10">receipt_long</i>
              </div>
              <span class="nav-link-text ms-1 {% if product %}{{product}}{% endif %}">Đơn hàng </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white {% if other_activate %}bg-gradient-primary{% endif %}" href="{% url 'admin_custom:admin_other' %}">
              <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                <i class="material-icons opacity-10">format_textdirection_r_to_l</i>
              </div>
              <span class="nav-link-text ms-1">Bảng tổng hợp</span>
            </a>
          </li>
    
          <li class="nav-item mt-3">
            <h6 class="ps-4 ms-2 text-uppercase text-xs text-white font-weight-bolder opacity-8">Quản lý tài khoản</h6>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white nav-link-activate" href="{% url 'admin_custom:sign_up' %}">
              <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                <i class="material-icons opacity-10">assignment</i>
              </div>
              <span class="nav-link-text ms-1">Đăng ký</span>
            </a>
          </li>
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'admin_custom:logout' %}?next=/admin_custom/login">
              <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                <i class="material-icons opacity-10">logout</i>
              </div>   
              <span class="nav-link-text ms-1">Đăng xuất</span>
            </a>
          </li>
          {% endif %}
       
        </ul>
      </div>
    </div>
  </div>
  <div class="col-9  col-md-9 col-lg-9 col-xl-10">
    <div class="main-content position-relative max-height-vh-100 h-100">
      <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur" data-scroll="true">
        <div class="container-fluid py-1 px-3">
          <nav aria-label="breadcrumb">
            <h6 class="font-weight-bolder mb-0">Giày là tất cả!</h6>
          </nav>
          <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
            <div class="ms-md-auto pe-md-3 d-flex align-items-center">
              <div class="input-group input-group-outline">
                <label class="form-label">Tìm kiếm</label>
                <input type="text" class="form-control">
              </div>
            </div>
            <ul class="navbar-nav  justify-content-end">
              <li class="nav-item d-flex align-items-center">
                {% if request.user.is_authenticated %}
                <a href="{% url 'admin_custom:logout' %}?next=/login" class="nav-link text-body font-weight-bold px-0">
                  <i class="fa fa-user me-sm-1"></i>
                  <span class="d-sm-inline d-none">Đăng xuất</span>
                </a>
                {% endif %}   
              </li>
              <li class="nav-item d-xl-none ps-3 d-flex align-items-center">
                <a href="javascript:;" class="nav-link text-body p-0" id="iconNavbarSidenav">
                  <div class="sidenav-toggler-inner">
                    <i class="sidenav-toggler-line"></i>
                    <i class="sidenav-toggler-line"></i>
                    <i class="sidenav-toggler-line"></i>
                  </div>
                </a>
              </li>
              <li class="nav-item px-3 d-flex align-items-center">
                <a href="javascript:;" class="nav-link text-body p-0">
                  <i class="fa fa-cog fixed-plugin-button-nav cursor-pointer"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <!-- End Navbar -->
      <div class="container-fluid px-2 px-md-4">
        <div class="page-header min-height-300 border-radius-xl mt-4" style="background-image: url('{% static 'admin_custom/img/logos/banner_admin.webp' %}');">
          <span class="mask  bg-gradient-primary  opacity-6"></span>
        </div>
        <div class="card card-body mx-3 mx-md-4 mt-n6">
          <div class="row gx-4 mb-2">
            <div class="col-auto">
              <div class="avatar avatar-xl position-relative">
                <img src="{% static 'admin_custom/img/logos/logo1.jpg' %}" alt="profile_image" class="w-100 border-radius-lg shadow-sm">
              </div>
            </div>
            <div class="col-auto my-auto">
              <div class="h-100">
                <h5 class="mb-1">
                  Tiệm giày chất
                </h5>
              </div>
            </div>
           
          </div>
        </div>
      </div>
   
    </div>
  </div>
</div>

  