shoe_store/shoe_store/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

shoe_store/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("store.urls")),
    path("admin_custom/",include("admin_custom.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views
app_name='shoe_store'
urlpatterns = [
    path('',views.main_shop,name='index'),
    path('trang-chu/',views.main_shop,name='index'),
    path('cua-hang/<slug:category>/', views.shop,name ="shop"),
    path('san-pham/<int:product_id>/', views.product_detail,name= "product_detail"),
     path('tim-kiem/', views.search,name= "search"),
    path('gio-hang/', views.cart,name= "cart"),
    path('thanh-toan/',views.checkout,name="checkout"),
    path('add_cart/',views.add_cart,name="add_cart"),
    path('remove_cart/',views.remove_cart,name="remove_cart"),
]

store/models.py
from django.db import models

# Create your models here.

admin_custom/forms.py
from django import forms
from .models import *
from django.forms import BaseInlineFormSet,inlineformset_factory
from django.utils.translation import gettext_lazy as _

class FormProduct(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
    name =  forms.CharField( widget=forms.TextInput(attrs={'class': 'form-control col-md-3 mb-2'}),label="Tên sản phẩm")   
    category = forms.ModelChoiceField(queryset=Category.objects.all(),widget=forms.Select(attrs={'class': 'form-control col-md-3 mb-2'}),label="Danh mục")
    price =  forms.CharField( widget=forms.NumberInput(attrs={'class': 'form-control col-md-3 mb-2'}),label="Giá gốc")
    accurate_price =  forms.CharField( widget=forms.NumberInput(attrs={'class': 'form-control col-md-3 mb-2'}),label="Giá chính thức")
    fabric =  forms.CharField( widget=forms.TextInput(attrs={'class': 'form-control col-md-3 mb-2'}),label="Chất liệu")     
    describe =  forms.CharField( widget=forms.TextInput(attrs={'class': 'form-control col-md-3 mb-2'}),label="Miêu tả sản phẩm")
    sale_percent = forms.ChoiceField(choices=SALE_PERCENT,widget=forms.Select(attrs={'class': 'form-control col-md-3 mb-2'}),label="%SALE")
    status = forms.ChoiceField(choices=STATUS,widget=forms.Select(attrs={'class': 'form-control col-md-3 mb-2'}),label="Trạng thái")
class FormInlineProduct(forms.ModelForm):
    class Meta:
        model = product_variants
        fields = '__all__'
 
    size = forms.ModelChoiceField(queryset=size_product.objects.all(),widget=forms.Select(attrs={'class': 'form-control col-md-4 mb-2'}),label="Kích cỡ")
    quantity =  forms.IntegerField( widget=forms.NumberInput(attrs={'class': 'form-control col-md-4 mb-2'}),label="Số lượng")   
    sku =  forms.CharField( widget=forms.TextInput(attrs={'class': 'form-control col-md-4 mb-2'}),label="Mã sản phẩm")
class FormInlineImg(forms.ModelForm):
    class Meta:
        model = Img_product
        fields = '__all__'
 
    img= forms.ImageField(allow_empty_file=False,label="Ảnh sản phẩm")
  
class FormOrder(forms.ModelForm):
    class Meta:
        model = Order
        fields = '__all__'
    customer_name =  forms.CharField( widget=forms.TextInput(attrs={'class': 'form-control col-md-3 mb-2'}),label="Tên khách hàng")   
    shipping_address =  forms.CharField( widget=forms.TextInput(attrs={'class': 'form-control col-md-3 mb-2'}),label="Địa chỉ nhận đơn")   
    phone_number =  forms.CharField( widget=forms.NumberInput(attrs={'class': 'form-control col-md-3 mb-2'}),label="Số điện thoại khách hàng")   
    email =  forms.EmailField( widget=forms.EmailInput(attrs={'class': 'form-control col-md-3 mb-2'}),label="Email khách hàng")
    total_price = forms.CharField( widget=forms.NumberInput(attrs={'class': 'form-control col-md-3 mb-2','readonly':''}),label="Tổng tiền đơn hàng")   
    order_description    =  forms.CharField( widget=forms.Textarea(attrs={'class': 'form-control col-md-3 mb-2'}),label="Ghi chú", required=False)
    status  = forms.ChoiceField(choices=STATUS_ORDER,widget=forms.Select(attrs={'class': 'form-control col-md-3 mb-2','hidden' :''}),label='')
    
class FormInlineOrder(forms.ModelForm):
    class Meta:
        model = Order_detail
        fields = '__all__'
    product = forms.ModelChoiceField(queryset=Product.objects.all(),widget=forms.Select(attrs={'class': 'form-control col-md-4 mb-2','disabled':''}),label="Tên giày")
    size = forms.IntegerField( widget=forms.NumberInput(attrs={'class': 'form-control  mb-2'}),label="Size")   
    quantity =  forms.IntegerField( widget=forms.NumberInput(attrs={'class': 'form-control mb-2'}),label="Số lượng")   
    def image_tag(self):
            img = Img_product.objects.filter(id_product = self.product).first()
            return mark_safe('<img src="%s" width="125" height="150" />' % (img.img.url))
    image_tag.short_description = 'Image'

class FormBanner(forms.ModelForm):
    class Meta:
        model = Banner
        fields = '__all__'
    title =  forms.CharField( widget=forms.TextInput(attrs={'class': 'form-control col-md-3 mb-2'}),label="Tiêu đề")  
    order = forms.IntegerField( widget=forms.NumberInput(attrs={'class': 'form-control  mb-2'}),label="Thứ tự")   
    
class FormSize(forms.ModelForm):
    class Meta:
        model = size_product
        fields = '__all__'
    size = forms.IntegerField( widget=forms.NumberInput(attrs={'class': 'form-control  mb-2'}),label="Size",required=True)   
    
class FormCategory(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'
    title = forms.CharField( widget=forms.TextInput(attrs={'class': 'form-control col-md-3 mb-2 title-category'}),label="Tiêu đề",required=True)  
    slug = forms.CharField( widget=forms.TextInput(attrs={'class': 'form-control col-md-3 mb-2'}),label="Miêu tả",required=True)  

class FormAboutContact(forms.ModelForm):
    class Meta:
        model = About_contact
        fields = '__all__'
    title =  forms.CharField( widget=forms.TextInput(attrs={'class': 'form-control col-md-3 mb-2'}),label="Tiêu đề") 
    about_describe =  forms.CharField( widget=forms.Textarea(attrs={'class': 'form-control col-md-3 mb-2'}),label="Lời tựa")  
    last_mes =  forms.CharField( widget=forms.TextInput(attrs={'class': 'form-control col-md-3 mb-2'}),label="Lời cuối")  
    facebook =  forms.CharField( widget=forms.TextInput(attrs={'class': 'form-control col-md-3 mb-2'}),label="Facebook")  
    instagram =  forms.CharField( widget=forms.TextInput(attrs={'class': 'form-control col-md-3 mb-2'}),label="Instagram")  
 



    
ProductFormsetVariant = inlineformset_factory(Product,product_variants,fields=('size','quantity','sku',),extra=1,form= FormInlineProduct,can_delete=True)
ProductFormsetImg = inlineformset_factory(Product,Img_product,fields=('img',),extra=3, form=FormInlineImg)
OrderFormset = inlineformset_factory(Order, Order_detail,fields = ('product','size','quantity',),extra=0,form=FormInlineOrder,exclude=('img_tag',))

store/views.py
from django.shortcuts import render,redirect
from admin_custom.models import *
from django.urls import reverse
from django.core.paginator import Paginator
from django.http import JsonResponse
from http import HTTPStatus
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.contrib import messages
# Create your views here.

def main_shop(request):
    count_cart = 0
    banner = Banner.objects.filter(is_activate = True).order_by('order')
    list_product_new =  Product.objects.filter(activate = True).order_by("-created_at")[:6]
    context = {
        'banner' : banner,
        'count_cart' : count_cart,
        'list_product_new' : list_product_new,
    }
    return render(request,"store/index.html",context)

def shop(request,category=None):
    sort_type= request.GET.get('sort_type', 'all')
    if category is not None and category != 'all':
        if sort_type == "low":
            list_product = Product.objects.filter(activate = True,category__title= category).order_by("accurate_price")
        elif sort_type == "high":
            list_product = Product.objects.filter(activate = True, category__title=category).order_by("-accurate_price")
        else:
            list_product = Product.objects.filter(activate = True,category__title=category).order_by('name')
    elif category == 'all' or category is None:
        if sort_type == "low":
            list_product = Product.objects.filter(activate = True).order_by("accurate_price")
        elif sort_type == "high":
            list_product = Product.objects.filter(activate = True).order_by("-accurate_price")
        else:
            list_product = Product.objects.filter(activate = True).order_by('name')
    product_paginator = Paginator(list_product,12)
    page_num = request.GET.get('page')
    
    page = product_paginator.get_page(page_num)
    if category == 'all' or category is None:
        context = {
            'count' : product_paginator.count,
            'page' : page,
            'sort_type' : sort_type,
            'category_name' : 'Tất Cả',
            'category' : category,
        }
    else:
         context = {
            'count' : product_paginator.count,
            'page' : page,
            'sort_type' : sort_type,
            'category_name' : category,
            'category' : category,
        }
    return render(request,"store/shop.html",context)

def product_detail(request,product_id):
        about = About_contact.objects.first()
        product = Product.objects.filter(id=product_id).first()
        product_size = product_variants.objects.filter(product_id = product_id)
      
        if product is not None:
            data_size = []
            for item in product_size:
                data_size.append(item.size.size)
            data_size.sort()
            img = Img_product.objects.filter(id_product = product_id)[:3]
            if product.activate == False:
                return redirect(reverse('shoe_store:shop'))
            context = { 
                'product' : product,
                'img' : img,
                'about' : about,
                'product_size'   : data_size,
            }
            return render(request,"store/product-details.html",context)
        else:
            return redirect(reverse('shoe_store:shop', kwargs={'category' : None}))

def cart(request):
    cart_id = None
    if 'cart' in request.session and request.session['cart'] and request.session['cart'] is not None:
        list_product = request.session['cart']
        total_price = 0
        for item in list_product:
            total_price += int(item['price'])
        context = {
            'list_product' : list_product,
            'total_price'  : total_price,
        }    
        return render(request,"store/cart.html",context)
    else:
         return render(request,"store/no_cart.html")

def checkout(request):
    if 'cart' in request.session and request.session['cart'] and request.session['cart'] is not None:
        list_product = request.session['cart']
        total_price = 0
        for item in list_product:
            total_price += int(item['price'])
        if request.method == 'POST':
            name =request.POST.get('name')
            address =request.POST.get('address')
            email =request.POST.get('email')
            phone_number =request.POST.get('phone')
            order_notes =request.POST.get('order_notes')
            check_email = None
            try:
                validate_email(email)
            except ValidationError as e:
                print("bad email, details:", e)
            else:
                check_email = True
            if name is not None and address is not None and check_email == True and phone_number is not None:
                try:
                    order =  Order.objects.create(customer_name = name, shipping_address = address,                           
                                                phone_number = phone_number, email = email, order_description = order_notes,total_price = total_price)
                    if order:
                        for item in list_product:
                            product_order = Product.objects.get(id = item['id'] )
                            if product_order:
                                order_detail =Order_detail.objects.create(order = order, product = product_order, size= item['size'],quantity = item['quantity'])
                            else:
                                Order.objects.delete(id = order.id)
                            del request.session['cart']
                            messages.success(request, ('Bạn đã đặt hàng thành công!'))
                            return redirect(reverse('shoe_store:shop',kwargs={'category' : None}))
                    else:
                        messages.error(request, ('Bạn đã đặt hàng thất bại!'))
                        return redirect(reverse('shoe_store:checkout'))  
                except Exception as e:
                    print(e)
                    messages.error(request, ('Bạn đã đặt hàng thất bại!'))
                    return redirect(reverse('shoe_store:checkout'))  
        context = {
            'list_product' : list_product,
            'total_price'  : total_price,
        }     
        return render(request,"store/checkout.html",context)
    else:
        return redirect(reverse('shoe_store:shop', kwargs={'category' : None}))
       
def add_cart(request):
    if request.is_ajax:
        product_id = request.POST.get('product_id')
        size = request.POST.get('size')
        quantity = request.POST.get('quantity')
        if 'cart' in request.session and request.session['cart'] and request.session['cart'] is not None:
            list_product = request.session['cart']
        else:
            list_product =[]
        if product_id:
            if list_product is not None:
                for item in list_product:
                    if item['id'] == product_id:
                         return JsonResponse({
                        'status': HTTPStatus.NOT_FOUND,
                        'message':'Sản phẩm đã có trong giỏ hàng !',
                        })
            product = Product.objects.get(id = product_id)
            img = Img_product.objects.filter(id_product = product_id).first()
            true_price = int(product.accurate_price) * int(quantity)
            id_product ={
               'id' : product_id,
               'name' : product.name,
               'url_img' : img.img.url,
               'price'  : true_price,
                'size' : size,
                'quantity' : quantity
            }
            list_product.append(id_product)
            request.session['cart'] = list_product
            print( HTTPStatus.OK)
            return JsonResponse({
                    'status': HTTPStatus.OK,
                    'message':'Sản phẩm được thêm vào giỏ hàng !',
                })
            
def remove_cart(request):
    if request.is_ajax :
        product_id = request.GET.get('product_id')
        if 'cart' in request.session and request.session['cart'] and request.session['cart'] is not None:
            list_cart = request.session['cart']
            new_list_cart = [item for item in list_cart if item['id'] != product_id]
            request.session['cart']  = new_list_cart
            option = ''
            total_price = 0
            for value in new_list_cart:
                total_price += int(value['price'])
                option += '<tr><td class="product-thumbnail"><img src="' + str(value['url_img']) +'"alt="Image" class="img-fluid"></td><td class="product-name"><h5>' + str(value['name']) + '</h5></td><td>'  + str(value['size']) + '</td><td>'+str(value['quantity'])+ '</td><td>' + str(value['price']) + '</td><td><a class="btn btn-black btn-sm btn-delete-cart-ajax" data-id="' + str(value['id']) +'">X</a></td></tr>'
            context = {
                'html': option,
                'total_price' : total_price
            }
            return JsonResponse(context)
        context = {
            'message': 'Invalid request'
        }
        return JsonResponse(context)
    
def search(request):
    check = False
    if request.method == "POST":
        name = request.POST.get('search')
        list_product = Product.objects.filter(name__contains = name)
        product_paginator = Paginator(list_product,12)
        page_num = request.GET.get('page')
        page = product_paginator.get_page(page_num)
        if list_product is not None:
            check = True
        context = {
            'count' : product_paginator.count,
            'page' : page,
            'check' : check
        }
        return render(request,"store/search.html",context)
    return redirect(reverse('shoe_store:index'))

# Create your views here.

templates/store/footer.html
{% load static %}
<div class="site-footer">

    <div class="container">
        <div class="row justify-content-between" style="color: #206430">
            <div class="col-lg-5">
                <div class="widget mb-4">
                    <h3 class="mb-2">{{about.title}}</h3>
                    <p>{{about.about_describe}}</p>
                </div>
                <div class="widget">
                    <h3>{{about.last_mes}}</h3>        
                </div>
            </div>
            <div class="col-lg-3">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d14906.371424293819!2d106.05226978780443!3d20.928693910711168!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3135a5666cc501c1%3A0x951d4b75688416cf!2zTmfDoyB0xrAgUGjhu5EgTuG7kWk!5e0!3m2!1svi!2s!4v1683383315154!5m2!1svi!2s" width="300" height="200" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>            </div>
        </div>


        <div class="row mt-2">
            <div class="col-12 text-center">
                <ul class="list-unstyled social">
                    <li><a href="{{about.facebook}}" target="_blank"><span class="icon-facebook"></span></a></li>
                    <li><a href="{{about.instagram}}"  target="_blank"><span class="icon-instagram"></span></a></li>
                    <li><a href="#"><span class="icon-linkedin"></span></a></li>
                    <li><a href="#"><span class="icon-twitter"></span></a></li>
                </ul>
            </div>
            <div class="col-12 text-center copyright">
                <p>Copyright &copy;<script>document.write(new Date().getFullYear());</script>. All Rights Reserved. &mdash; Designed with love by <a href="https://www.facebook.com/quan.dinh.581525">Quan</a>
                </p>

            </div>
        </div>
    </div> <!-- /.container -->
</div> <!-- /.site-footer -->

<div id="overlayer"></div>
<div class="loader">
    <div class="spinner-border" role="status">
        <span class="sr-only">Loading...</span>
    </div>
</div>

templates/store/head.html
{% load static %}

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="author" content="Untree.co">
<link rel="shortcut icon" type="image/x-icon" href="{% static 'admin_custom/img/logos/logo1.jpg' %}" />

<meta name="description" content="" />
<meta name="keywords" content="" />

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Mulish:ital,wght@0,300;0,400;0,700;1,700&family=Playfair+Display:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">


<link rel="stylesheet" href="{% static 'store/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'store/css/animate.min.css'%}">
<link rel="stylesheet" href="{% static 'store/css/owl.carousel.min.css' %}">
<link rel="stylesheet" href="{% static 'store/css/owl.theme.default.min.css'%}">
<link rel="stylesheet" href="{% static 'store/css/jquery.fancybox.min.css'%}">
<link rel="stylesheet" href="{% static 'store/fonts/icomoon/style.css'%} ">
<link rel="stylesheet" href="{% static 'store/fonts/flaticon/font/flaticon.css'%} ">
<link rel="stylesheet" href="{% static 'store/css/aos.css'%}">
<link rel="stylesheet" href="{% static 'store/css/style.css' %}">

templates/store/index.html
{% extends 'store/layout.html' %}
{% load shop_tags%}
{% load static %}
{% load humanize %}
{% block body_content  %}
<div class="owl-carousel owl-single home-slider">
	{% for item in banner  %}
	<div class="item">
		<div class="untree_co-hero" style="background-image: url('{{item.image.url}}');">
			<div class="container">
				<div class="row align-items-center">
					<div class="col-lg-6">

						<h1 class="mb-4 heading" data-aos="fade-up" data-aos-delay="100">{{item.title}}<a href="{% url 'shoe_store:shop' 'all' %}"></a></h1>
						<div class="mb-5 text-white desc mx-auto" data-aos="fade-up" data-aos-delay="200">
						</div>

						<p class="mb-0" data-aos="fade-up" data-aos-delay="300"><a href="{% url 'shoe_store:shop' 'all' %}" class="btn btn-outline-black">Shop Now</a></p>

					</div>
				</div>
			</div>
		</div> <!-- /.untree_co-hero -->
	</div>
	{% endfor %}
</div>





<div class="untree_co-section">
	<div class="container">


		<div class="deal-hero overlay" style="background-image: url('{% static 'admin_custom/img/banner/second_Banner.jpg' %}')"> 
			<div class="deal-contents">
				<span class="subtitle">SALE đén 70%</span>
				<h2 class="title mb-4"><a href="#">Hè rực rỡ!</a></h2>
				<p class="mb-5"></p>
			</div>
		</div> <!-- /.deal-hero -->

	</div>
</div>
	<div class="untree_co-section">
		<div class="container">
			<h2 class="h3"><span class="text-danger">Hàng mới</span></h2>     
			<div class="row">
				{% for item in list_product_new  %}
				<div class="col-6 col-sm-6 col-md-6 mb-4 col-lg-4">
					<div class="product-item">
						<a href="{% url 'shoe_store:product_detail' item.id %}" class="product-img">
							<div class="label new top-right">
								<div class='content'>New</div>
							</div>
							<img src="{% get_img_product item.id %}" alt="Image" class="img-fluid">
						</a>
						<h3 class="title"><a href="#">{{item.name}}</a></h3>
						<div class="price">
							 <span >{{item.accurate_price|intcomma}} đ</span>
						</div>
					</div>
				</div>

				{% endfor %}
			</div>
		</div>
	</div> <!-- /.untree_co-section -->




<div class="untree_co-section">
    <div class="container">
      <div class="row mb-5 align-items-center">
        <div class="col-md-6">
          <h2 class="h3"><span class="text-danger">SALE</span></h2>        
        </div>
        <div class="col-sm-6 carousel-nav text-sm-right">
          <a href="#" class="prev js-custom-prev-v2">
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-left-circle" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
              <path fill-rule="evenodd" d="M8.354 11.354a.5.5 0 0 0 0-.708L5.707 8l2.647-2.646a.5.5 0 1 0-.708-.708l-3 3a.5.5 0 0 0 0 .708l3 3a.5.5 0 0 0 .708 0z"/>
              <path fill-rule="evenodd" d="M11.5 8a.5.5 0 0 0-.5-.5H6a.5.5 0 0 0 0 1h5a.5.5 0 0 0 .5-.5z"/>
            </svg>
          </a>
          <a href="#" class="next js-custom-next-v2">
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-right-circle" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
              <path fill-rule="evenodd" d="M7.646 11.354a.5.5 0 0 1 0-.708L10.293 8 7.646 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0z"/>
              <path fill-rule="evenodd" d="M4.5 8a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1H5a.5.5 0 0 1-.5-.5z"/>
            </svg>
          </a>
        </div>
      </div> <!-- /.heading -->
	  {% render_sale_product %}
    </div> <!-- /.container -->
  </div> <!-- /.untree_co-section -->  

{% endblock  %}

	

templates/store/navbar.html
{% load static  %}

<div class="search-form" id="search-form">
	<form action=" {% url 'shoe_store:search' %}" method="POST">
		{% csrf_token %}
		<input type="search" class="form-control" placeholder="Tên sản phẩm muốn tìm..." name="search">
		<button class="button">
			<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-search" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
				<path fill-rule="evenodd" d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z"/>
				<path fill-rule="evenodd" d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z"/>
			</svg>
		</button>
		<button class="button" type="submit">
			<div class="close-search">
				<span class="icofont-close js-close-search"></span>
			</div>
		</button>

	</form>
</div>

<div class="site-mobile-menu">
	<div class="site-mobile-menu-header">
		<div class="site-mobile-menu-close">
			<span class="icofont-close js-menu-toggle"></span>
		</div>
	</div>
	<div class="site-mobile-menu-body"></div>
</div>


<nav class="site-nav mb-5">
	<div class="sticky-nav js-sticky-header">
		<div class="container position-relative">
			<div class="site-navigation text-center dark">
				<a href="{% url 'shoe_store:index' %}" class="logo menu-absolute m-0"><img src="{% static 'admin_custom/img/logos/logo1.jpg' %}" style="max-width:120px;max-height:50px;;"><span class="text-primary"></span></a>

				<ul class="js-clone-nav pl-0 d-none d-lg-inline-block site-menu">
					<li class="active"><a href="{% url 'shoe_store:index' %}">Trang chủ</a></li>
					<li class="has-children">
						<a href="{% url 'shoe_store:shop' 'all' %}">Cửa hàng</a>
						<ul class="dropdown">
							{% if category %}
							{% for item in  category %}
							<li><a href="{% url 'shoe_store:shop' item.title %}" class="text-uppercase">{{item.title}}</a></li>
							{% endfor %}
							
							{% endif %}
							
						</ul>
					</li>
					<li class="has-children">
						<a href="{% url 'shoe_store:checkout' %}">Thanh toán</a>
						<ul class="dropdown">
							<li><a href="{% url 'shoe_store:cart' %}">Giỏ hàng</a></li>
							<li><a href="{% url 'shoe_store:checkout'  %}">Thanh toán</a></li>
						</ul>
					</li>
					
				</ul>
				<div class="menu-icons">

					<a href="#" class="btn-custom-search" id="btn-search">
						<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-search" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
							<path fill-rule="evenodd" d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z"/>
							<path fill-rule="evenodd" d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z"/>
						</svg>
					</a>



					<a href="{% url 'shoe_store:cart' %}" class="cart">
						<span class="item-in-cart" data-cart="{% if request.session.cart  %}{{request.session.cart |length}}{% else %}0{% endif %}"> {% if request.session.cart  %}{{request.session.cart |length}}{% else %}0{% endif %}</span>
						<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-cart" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
							<path fill-rule="evenodd" d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm7 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/>
						</svg>
					</a>

				</div>

				<a href="#" class="burger ml-auto float-right site-menu-toggle js-menu-toggle d-inline-block d-lg-none" data-toggle="collapse" data-target="#main-navbar">
					<span></span>
				</a>

			</div>
		</div>
	</div>
</nav>